In [2]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,3,5])



[3 2 7]


In [ ]:
#addition of two vectos 
print(v+w)

[3 2 7]


In [7]:
#substraction of two vectors
print(v-w)

[-1 -4 -3]


In [8]:
#scalar multiplication 
print(3*v)

[ 3 -3  6]


In [9]:
#magnitude of vectors / length of vectors 
print(np.linalg.norm(v))

2.449489742783178


In [10]:
#dot product of two vectors 
print(np.dot(v,w))

9
