In [1]:
import numpy as np


In [4]:
p= np.array([[1,7],[2,1],[3,2]])
print(p)#we get 3x2 matrix

[[1 7]
 [2 1]
 [3 2]]


In [5]:
q=np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [6]:
c1 = np.add(p,q) #additon of 2 matrix
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [8]:
c2 = np.subtract(p,q) #substraction of 2 matrix
print(c2)

[[0 6]
 [1 2]
 [2 2]]


In [10]:
r = np.array([[2,1,2],[3,4,5]])
print(r)

[[2 1 2]
 [3 4 5]]


In [11]:
s = np.array([[2,3,4,5],[2,3,5,6],[2,5,7,8]])
print(s)

[[2 3 4 5]
 [2 3 5 6]
 [2 5 7 8]]


In [12]:
c3=np.dot(r,s) #multiplication of 3 matrix
print(c3) 

[[10 19 27 32]
 [24 46 67 79]]


In [13]:
t = np.array([[1,4],[2,4]])
print(t) #here we get the 2x2 matrix


[[1 4]
 [2 4]]


In [14]:
c4=np.linalg.det(t) #determinant of matrix t
print(c4)

-4.0


In [15]:
c5 = np.linalg.inv(t) #inverse of matrix t 
print(c5)

[[-1.    1.  ]
 [ 0.5  -0.25]]
