In [13]:
import numpy as np 


In [14]:
l1 = [10,20, 40]
l2 = [14, 34, 55]
print(l1+l2)



[10, 20, 40, 14, 34, 55]


In [15]:
a = np.array([10 , 20, 30])
b = np.array([40,50,566])
print(a) 
print(b) 
print(a+b)
print(a*b) 
print(a/b)


[10 20 30]
[ 40  50 566]
[ 50  70 596]
[  400  1000 16980]
[0.25       0.4        0.05300353]


In [16]:
c = np.array([4])
print(a+c)
print(a*c)

[14 24 34]
[ 40  80 120]


In [17]:
d= np.array([10,20 ,'10'])
print(d)

['10' '20' '10']


In [18]:
e = np.array([[20,30,40], [30 ,40 ,50]])
print(e)

[[20 30 40]
 [30 40 50]]


: 