In [9]:

import numpy as np


In [7]:
arr1=np.array([30,40,60,20,10])
arr2 =np.array([30,20,10,20,20])
print(arr1,arr2)

[30 40 60 20 10] [30 20 10 20 20]


In [8]:
print(np.add(arr1,arr2))

[60 60 70 40 30]


In [16]:
a = np.array([[20,30],[20,30]])
b = np.array([[30,20],[10,40]])
print(a-b)
print()
print(np.subtract(a,b))



[[-10  10]
 [ 10 -10]]

[[-10  10]
 [ 10 -10]]


In [17]:
print(a/b)
print(np.divide(a,b))


[[0.66666667 1.5       ]
 [2.         0.75      ]]
[[0.66666667 1.5       ]
 [2.         0.75      ]]


In [18]:
c = np.array([3])
d  =np.power(a,c)
print(d)


[[ 8000 27000]
 [ 8000 27000]]


In [19]:
print(np.sqrt(d))

[[ 89.4427191  164.31676725]
 [ 89.4427191  164.31676725]]


In [20]:
#combining and splitting arrays
import numpy as np 
a = [30,40,50]
b = [3,4,5]
print(a+b)

[30, 40, 50, 3, 4, 5]


In [26]:
#concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([4,5,'6'])




In [28]:


a = np.array([20,30,50,60])
print(np.append(a,40))

[20 30 50 60 40]


In [30]:
b = np.array([[20,40],[40,50]])
print(np.append(b,[10,40]))

[20 40 40 50 10 40]


In [31]:
print(np.insert(b,3,[345,56]))

[ 20  40  40 345  56  50]


IndexError: index 2 is out of bounds for axis 0 with size 2