In [7]:
import numpy as np 


In [8]:
arr = np.array([10,20,40,30])
print(arr)
print(arr[0:3])
print(arr[:4])
print(arr[3:4])
print(arr[:3])
print(arr[2:])


[10 20 40 30]
[10 20 40]
[10 20 40 30]
[30]
[10 20 40]
[40 30]


In [11]:
a = np.array([[10,20,30,40],[20,45,50, 35],[34,45,56,56]])
print(a)
print(a[0:3 ,1:3])
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))
print(a.dtype)



[[10 20 30 40]
 [20 45 50 35]
 [34 45 56 56]]
[[20 30]
 [45 50]
 [45 56]]
(3, 4)
12
2
int32


: 